function Iw_en = Iw(beta,a,b,p,A,B,P,K)

Iw_en = ((beta*((2*b(1))+1)*primitive_integral(a,b,p,A,B,P,K))...
            - ((2*(beta^2))*primitive_integral(a,b+[2 0 0],p,A,B,P,K))...
            - (0.5*b(1)*(b(1)-1) * primitive_integral(a,b-[2 0 0],p,A,B,P,K)))...
            ...
            + ((beta*((2*b(2))+1)*primitive_integral(a,b,p,A,B,P,K))...
            - ((2*(beta^2))*primitive_integral(a,b+[0 2 0],p,A,B,P,K))...
            - (0.5*b(2)*(b(2)-1) * primitive_integral(a,b-[0 2 0],p,A,B,P,K)))...
            ...
            + ((beta*((2*b(3))+1)*primitive_integral(a,b,p,A,B,P,K))...
            - ((2*(beta^2))*primitive_integral(a,b+[0 0 2],p,A,B,P,K))...
            - (0.5*b(3)*(b(3)-1) * primitive_integral(a,b-[0 0 2],p,A,B,P,K)));

end